spring:
  application.name: flink-jobs
  cassandra:
    contact-points: ${CASSANDRA_HOST:localhost}
    keyspace: analytics
    port: 9042
    local-datacenter: datacenter1
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092,localhost:9094}
    topic: app.messages
    groupId: app-messages
  minio:
    bucket: click-analysis
    input-path: local/
    watch-interval: 60000
