global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'generator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8092' ]
        labels:
          application: 'generator'
  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
        labels:
          application: 'api'
  - job_name: 'minio-to-cassandra'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8093' ]
        labels:
          application: 'minio-to-cassandra'
  - job_name: 'kafka-to-cassandra'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8094' ]
        labels:
          application: 'kafka-to-cassandra'
  - job_name: 'cassandra-to-cassandra'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8095' ]
        labels:
          application: 'cassandra-to-cassandra'