global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'generator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8092' ]
        labels:
          application: 'generator'
  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
        labels:
          application: 'api'