apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Clickhouse
    type: grafana-clickhouse-datasource
    orgId: 1
    access: proxy
    url: http://host.docker.internal:8123
    basicAuth: false
    editable: true
    jsonData:
      defaultDatabase: analytics
      port: 9002
      host: host.docker.internal
      username: admin
      tlsSkipVerify: false
    secureJsonData:
      password: admin