spring:
  application.name: api
  cassandra:
    keyspace-name: clickstream
    contact-points: ${CASSANDRA_HOST:localhost}
    port: 9042
    local-datacenter: DC1
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    ssl.enabled: false

server:
  port: 8080

management:
  server.port: 8091
  endpoint:
    health.access: read_only
    info.access: read_only
    metrics.access: unrestricted
    prometheus.access: unrestricted
    loggers.access: read_only
  endpoints.web.exposure.include: health,info,prometheus,metrics,loggers
